WIP: Added insertions/deletions/lines properities for easy commit info collection in commit.py
ishepard/pydriller pull request #151
Opened 2020-12-31 17:13 UTC by butterl

Added insertions/deletions/lines properities for easy commit info collection

From phrase the gitpython classgit.util.Stats(total, files) it could give the data we need
https://gitpython.readthedocs.io/en/stable/reference.html?highlight=stats.total#git.util.Stats

2020-12-31 17:15 UTC, butterl commented
since I'm not so familiar with python and do not got a runable python env at hand  , this is only what I thought may work and edit in github webpage , need test when I got more  time read through the code

2021-01-01 16:22 UTC, ishepard commented
Hi @butterl!
Thanks for the PR. That looks nice, add some tests and then we see how it works!

BTW: I think you should also add `total["files"]`, that is the number of files modified in the commit.

2021-01-01 18:21 UTC, butterl commented
Since I changed the code in chrome brower directly , the commits not squashed into one , maybe the squash could be done directly while merge ,or I need start a new pr?

2021-01-02 13:00 UTC, ishepard requested changes

2021-01-02 13:00 UTC, ishepard commented on pydriller/domain/commit.py
> +        return len(self._c_object.stats.files)
```suggestion
        return self._c_object.stats.total["files"]
```

2021-01-02 13:04 UTC, ishepard commented on pydriller/domain/commit.py
> +        return len(self._c_object.stats.files)
According to [this](https://gitpython.readthedocs.io/en/stable/reference.html?highlight=stats.total#git.util.Stats), `total["files"]` should be the number of changed files as int

2021-01-03 11:29 UTC, ishepard approved these changes

2021-01-04 09:54 UTC, ishepard commented
Thanks for the PR! I will add more tests and then I will publish a new version of Pydriller. Thanks again!

2021-01-04 09:54 UTC, merged